Fix "Attempted to read an unowned reference..."
 When the BackgroundTaskRegistrar instance is deallocated before iOS fires the expiration handler, the unowned reference causes a      
  crash:                                                                                                                                
                                                                                                                                        
  Fatal error: Attempted to read an unowned reference but object 0x… was already deallocated                                            
                                                                                                                                        
  Stack Trace                                                                                                                           
                                                                                                                                        
  at swift_nonatomic_unownedRetainStrong                                                                                                
  at closure #1 in BackgroundTaskRegistrar.register(name:completion:) (BackgroundTaskRegistering.swift:19)                              
  at -[_UIBackgroundTaskInfo fireExpirationHandler]